window.GROUPS = [
 {
  "title": "Institut Consell de Cent",
  "group": "ESO 1r A",
  "term": "Trimestre 3",
  "subjects": [
   "BIOLOGIA",
   "MATEMÀTIQUES",
   "TECNOLOGIA I DIGITALITZACIÓ",
   "TREBALL GLOBALITZAT",
   "EDUCACIÓ FÍSICA",
   "EDUCACIÓ VISUAL I PLÀSTICA",
   "MÚSICA",
   "Aula d'Acollida",
   "LLENG ANGLESA",
   "LLENG CASTELLANA",
   "LLENG CATALANA",
   "LLENG FRANCESA",
   "CIÈNCIES SOCIALS",
   "CULTURA CLÀSSICA",
   "OPTATIVA TEATRE",
   "RELIGIÓ"
  ],
  "students": [
   {
    "id": 1,
    "grades": {
     "BIOLOGIA": "AN",
     "MATEMÀTIQUES": "AN",
     "TECNOLOGIA I DIGITALITZACIÓ": "AE",
     "TREBALL GLOBALITZAT": "AN",
     "EDUCACIÓ FÍSICA": "AS",
     "EDUCACIÓ VISUAL I PLÀSTICA": "AE",
     "MÚSICA": "AE",
     "Aula d'Acollida": null,
     "LLENG ANGLESA": "AE",
     "LLENG CASTELLANA": "AN",
     "LLENG CATALANA": "AN",
     "LLENG FRANCESA": null,
     "CIÈNCIES SOCIALS": "AE",
     "CULTURA CLÀSSICA": "AS",
     "OPTATIVA TEATRE": null,
     "RELIGIÓ": null
    },
    "avg": 8.13,
    "fails": 0
   },
   {
    "id": 2,
    "grades": {
     "BIOLOGIA": "AS",
     "MATEMÀTIQUES": "AS",
     "TECNOLOGIA I DIGITALITZACIÓ": "NA",
     "TREBALL GLOBALITZAT": "AS",
     "EDUCACIÓ FÍSICA": "AS",
     "EDUCACIÓ VISUAL I PLÀSTICA": "AN",
     "MÚSICA": "AN",
     "Aula d'Acollida": null,
     "LLENG ANGLESA": "AS",
     "LLENG CASTELLANA": "NA",
     "LLENG CATALANA": "AS",
     "LLENG FRANCESA": "AS",
     "CIÈNCIES SOCIALS": "NA",
     "CULTURA CLÀSSICA": null,
     "OPTATIVA TEATRE": null,
     "RELIGIÓ": null
    },
    "avg": 4.88,
    "fails": 3
   },
   {
    "id": 3,
    "grades": {
     "BIOLOGIA": "AS",
     "MATEMÀTIQUES": "AS",
     "TECNOLOGIA I DIGITALITZACIÓ": "AS",
     "TREBALL GLOBALITZAT": "AS",
     "EDUCACIÓ FÍSICA": "AN",
     "EDUCACIÓ VISUAL I PLÀSTICA": "AN",
     "MÚSICA": "AS",
     "Aula d'Acollida": null,
     "LLENG ANGLESA": "AN",
     "LLENG CASTELLANA": "NA",
     "LLENG CATALANA": "NA",
     "LLENG FRANCESA": "AS",
     "CIÈNCIES SOCIALS": "NA",
     "CULTURA CLÀSSICA": null,
     "OPTATIVA TEATRE": null,
     "RELIGIÓ": null
    },
    "avg": 5.13,
    "fails": 3
   },
   {
    "id": 4,
    "grades": {
     "BIOLOGIA": "AS",
     "MATEMÀTIQUES": "AS",
     "TECNOLOGIA I DIGITALITZACIÓ": "AS",
     "TREBALL GLOBALITZAT": "AN",
     "EDUCACIÓ FÍSICA": "AN",
     "EDUCACIÓ VISUAL I PLÀSTICA": "NA",
     "MÚSICA": "AS",
     "Aula d'Acollida": null,
     "LLENG ANGLESA": "AS",
     "LLENG CASTELLANA": "NA",
     "LLENG CATALANA": "NA",
     "LLENG FRANCESA": "NA",
     "CIÈNCIES SOCIALS": "NA",
     "CULTURA CLÀSSICA": null,
     "OPTATIVA TEATRE": null,
     "RELIGIÓ": null
    },
    "avg": 4.46,
    "fails": 5
   },
   {
    "id": 5,
    "grades": {
     "BIOLOGIA": "NA",
     "MATEMÀTIQUES": "NA",
     "TECNOLOGIA I DIGITALITZACIÓ": "NA",
     "TREBALL GLOBALITZAT": "AN",
     "EDUCACIÓ FÍSICA": "AS",
     "EDUCACIÓ VISUAL I PLÀSTICA": "AE",
     "MÚSICA": "NA",
     "Aula d'Acollida": null,
     "LLENG ANGLESA": "AE",
     "LLENG CASTELLANA": "AS",
     "LLENG CATALANA": "AN",
     "LLENG FRANCESA": null,
     "CIÈNCIES SOCIALS": "NA",
     "CULTURA CLÀSSICA": null,
     "OPTATIVA TEATRE": null,
     "RELIGIÓ": null
    },
    "avg": 5.23,
    "fails": 5
   },
   {
    "id": 6,
    "grades": {
     "BIOLOGIA": "NA",
     "MATEMÀTIQUES": "AS",
     "TECNOLOGIA I DIGITALITZACIÓ": "AS",
     "TREBALL GLOBALITZAT": "AS",
     "EDUCACIÓ FÍSICA": "AS",
     "EDUCACIÓ VISUAL I PLÀSTICA": "AS",
     "MÚSICA": "NA",
     "Aula d'Acollida": null,
     "LLENG ANGLESA": "AN",
     "LLENG CASTELLANA": "NA",
     "LLENG CATALANA": "NA",
     "LLENG FRANCESA": null,
     "CIÈNCIES SOCIALS": "AS",
     "CULTURA CLÀSSICA": "NA",
     "OPTATIVA TEATRE": null,
     "RELIGIÓ": null
    },
    "avg": 4.21,
    "fails": 5
   },
   {
    "id": 7,
    "grades": {
     "BIOLOGIA": "NA",
     "MATEMÀTIQUES": "AS",
     "TECNOLOGIA I DIGITALITZACIÓ": "NA",
     "TREBALL GLOBALITZAT": "AS",
     "EDUCACIÓ FÍSICA": "AS",
     "EDUCACIÓ VISUAL I PLÀSTICA": "AN",
     "MÚSICA": "NA",
     "Aula d'Acollida": null,
     "LLENG ANGLESA": "NA",
     "LLENG CASTELLANA": "NA",
     "LLENG CATALANA": "AS",
     "LLENG FRANCESA": null,
     "CIÈNCIES SOCIALS": "AN",
     "CULTURA CLÀSSICA": null,
     "OPTATIVA TEATRE": null,
     "RELIGIÓ": null
    },
    "avg": 4.41,
    "fails": 5
   },
   {
    "id": 8,
    "grades": {
     "BIOLOGIA": "AS",
     "MATEMÀTIQUES": "AS",
     "TECNOLOGIA I DIGITALITZACIÓ": "AS",
     "TREBALL GLOBALITZAT": "AN",
     "EDUCACIÓ FÍSICA": "AN",
     "EDUCACIÓ VISUAL I PLÀSTICA": "AN",
     "MÚSICA": "AE",
     "Aula d'Acollida": null,
     "LLENG ANGLESA": "AS",
     "LLENG CASTELLANA": "AS",
     "LLENG CATALANA": "AN",
     "LLENG FRANCESA": "AS",
     "CIÈNCIES SOCIALS": "AN",
     "CULTURA CLÀSSICA": null,
     "OPTATIVA TEATRE": null,
     "RELIGIÓ": null
    },
    "avg": 6.63,
    "fails": 0
   },
   {
    "id": 9,
    "grades": {
     "BIOLOGIA": "AS",
     "MATEMÀTIQUES": "AS",
     "TECNOLOGIA I DIGITALITZACIÓ": "AE",
     "TREBALL GLOBALITZAT": "AS",
     "EDUCACIÓ FÍSICA": "AN",
     "EDUCACIÓ VISUAL I PLÀSTICA": "AN",
     "MÚSICA": "AS",
     "Aula d'Acollida": "AN",
     "LLENG ANGLESA": "AS",
     "LLENG CASTELLANA": "AS",
     "LLENG CATALANA": "AN",
     "LLENG FRANCESA": null,
     "CIÈNCIES SOCIALS": "AS",
     "CULTURA CLÀSSICA": "AN",
     "OPTATIVA TEATRE": null,
     "RELIGIÓ": null
    },
    "avg": 6.5,
    "fails": 0
   },
   {
    "id": 10,
    "grades": {
     "BIOLOGIA": "AN",
     "MATEMÀTIQUES": "AN",
     "TECNOLOGIA I DIGITALITZACIÓ": "AN",
     "TREBALL GLOBALITZAT": "AE",
     "EDUCACIÓ FÍSICA": "AS",
     "EDUCACIÓ VISUAL I PLÀSTICA": "AE",
     "MÚSICA": "AN",
     "Aula d'Acollida": null,
     "LLENG ANGLESA": "AS",
     "LLENG CASTELLANA": "AS",
     "LLENG CATALANA": "AS",
     "LLENG FRANCESA": null,
     "CIÈNCIES SOCIALS": "AN",
     "CULTURA CLÀSSICA": "AS",
     "OPTATIVA TEATRE": null,
     "RELIGIÓ": null
    },
    "avg": 7.0,
    "fails": 0
   },
   {
    "id": 11,
    "grades": {
     "BIOLOGIA": "AS",
     "MATEMÀTIQUES": "AS",
     "TECNOLOGIA I DIGITALITZACIÓ": "NA",
     "TREBALL GLOBALITZAT": "AN",
     "EDUCACIÓ FÍSICA": "AS",
     "EDUCACIÓ VISUAL I PLÀSTICA": "AN",
     "MÚSICA": "AN",
     "Aula d'Acollida": null,
     "LLENG ANGLESA": "AS",
     "LLENG CASTELLANA": "NA",
     "LLENG CATALANA": "AS",
     "LLENG FRANCESA": null,
     "CIÈNCIES SOCIALS": "NA",
     "CULTURA CLÀSSICA": "NA",
     "OPTATIVA TEATRE": null,
     "RELIGIÓ": null
    },
    "avg": 4.92,
    "fails": 4
   },
   {
    "id": 12,
    "grades": {
     "BIOLOGIA": "AS",
     "MATEMÀTIQUES": "NA",
     "TECNOLOGIA I DIGITALITZACIÓ": "AS",
     "TREBALL GLOBALITZAT": "AS",
     "EDUCACIÓ FÍSICA": "AS",
     "EDUCACIÓ VISUAL I PLÀSTICA": "AS",
     "MÚSICA": "AS",
     "Aula d'Acollida": null,
     "LLENG ANGLESA": "AS",
     "LLENG CASTELLANA": "NA",
     "LLENG CATALANA": "AS",
     "LLENG FRANCESA": null,
     "CIÈNCIES SOCIALS": "NA",
     "CULTURA CLÀSSICA": null,
     "OPTATIVA TEATRE": null,
     "RELIGIÓ": "AS"
    },
    "avg": 4.38,
    "fails": 3
   },
   {
    "id": 13,
    "grades": {
     "BIOLOGIA": "AN",
     "MATEMÀTIQUES": "AE",
     "TECNOLOGIA I DIGITALITZACIÓ": "AE",
     "TREBALL GLOBALITZAT": "AE",
     "EDUCACIÓ FÍSICA": "AE",
     "EDUCACIÓ VISUAL I PLÀSTICA": "AN",
     "MÚSICA": "AE",
     "Aula d'Acollida": null,
     "LLENG ANGLESA": "AE",
     "LLENG CASTELLANA": "AN",
     "LLENG CATALANA": "AN",
     "LLENG FRANCESA": "AE",
     "CIÈNCIES SOCIALS": "AE",
     "CULTURA CLÀSSICA": null,
     "OPTATIVA TEATRE": null,
     "RELIGIÓ": null
    },
    "avg": 9.0,
    "fails": 0
   },
   {
    "id": 14,
    "grades": {
     "BIOLOGIA": "AS",
     "MATEMÀTIQUES": "NA",
     "TECNOLOGIA I DIGITALITZACIÓ": "AS",
     "TREBALL GLOBALITZAT": "AS",
     "EDUCACIÓ FÍSICA": "AS",
     "EDUCACIÓ VISUAL I PLÀSTICA": "AS",
     "MÚSICA": "AN",
     "Aula d'Acollida": null,
     "LLENG ANGLESA": "NA",
     "LLENG CASTELLANA": "NA",
     "LLENG CATALANA": "NA",
     "LLENG FRANCESA": null,
     "CIÈNCIES SOCIALS": "NA",
     "CULTURA CLÀSSICA": null,
     "OPTATIVA TEATRE": null,
     "RELIGIÓ": null
    },
    "avg": 4.14,
    "fails": 5
   },
   {
    "id": 15,
    "grades": {
     "BIOLOGIA": "AN",
     "MATEMÀTIQUES": "AS",
     "TECNOLOGIA I DIGITALITZACIÓ": "AS",
     "TREBALL GLOBALITZAT": "AS",
     "EDUCACIÓ FÍSICA": "AN",
     "EDUCACIÓ VISUAL I PLÀSTICA": "AN",
     "MÚSICA": "AS",
     "Aula d'Acollida": null,
     "LLENG ANGLESA": "AS",
     "LLENG CASTELLANA": "AS",
     "LLENG CATALANA": "AS",
     "LLENG FRANCESA": "AN",
     "CIÈNCIES SOCIALS": "NA",
     "CULTURA CLÀSSICA": null,
     "OPTATIVA TEATRE": null,
     "RELIGIÓ": null
    },
    "avg": 5.79,
    "fails": 1
   },
   {
    "id": 16,
    "grades": {
     "BIOLOGIA": "AS",
     "MATEMÀTIQUES": "AS",
     "TECNOLOGIA I DIGITALITZACIÓ": "AS",
     "TREBALL GLOBALITZAT": "AE",
     "EDUCACIÓ FÍSICA": "AN",
     "EDUCACIÓ VISUAL I PLÀSTICA": "AN",
     "MÚSICA": "AN",
     "Aula d'Acollida": null,
     "LLENG ANGLESA": "AE",
     "LLENG CASTELLANA": "AS",
     "LLENG CATALANA": "AS",
     "LLENG FRANCESA": "AN",
     "CIÈNCIES SOCIALS": "AN",
     "CULTURA CLÀSSICA": null,
     "OPTATIVA TEATRE": null,
     "RELIGIÓ": null
    },
    "avg": 7.0,
    "fails": 0
   },
   {
    "id": 17,
    "grades": {
     "BIOLOGIA": "AS",
     "MATEMÀTIQUES": "AS",
     "TECNOLOGIA I DIGITALITZACIÓ": "AS",
     "TREBALL GLOBALITZAT": "AE",
     "EDUCACIÓ FÍSICA": "AS",
     "EDUCACIÓ VISUAL I PLÀSTICA": "AN",
     "MÚSICA": "AS",
     "Aula d'Acollida": null,
     "LLENG ANGLESA": "AE",
     "LLENG CASTELLANA": "NA",
     "LLENG CATALANA": "AN",
     "LLENG FRANCESA": "AS",
     "CIÈNCIES SOCIALS": "AN",
     "CULTURA CLÀSSICA": null,
     "OPTATIVA TEATRE": null,
     "RELIGIÓ": null
    },
    "avg": 6.29,
    "fails": 1
   },
   {
    "id": 18,
    "grades": {
     "BIOLOGIA": "AN",
     "MATEMÀTIQUES": "AS",
     "TECNOLOGIA I DIGITALITZACIÓ": "AS",
     "TREBALL GLOBALITZAT": "AN",
     "EDUCACIÓ FÍSICA": "AS",
     "EDUCACIÓ VISUAL I PLÀSTICA": "AN",
     "MÚSICA": "AE",
     "Aula d'Acollida": null,
     "LLENG ANGLESA": "NA",
     "LLENG CASTELLANA": "AS",
     "LLENG CATALANA": "NA",
     "LLENG FRANCESA": null,
     "CIÈNCIES SOCIALS": "NA",
     "CULTURA CLÀSSICA": null,
     "OPTATIVA TEATRE": null,
     "RELIGIÓ": "AE"
    },
    "avg": 5.88,
    "fails": 3
   }
  ]
 },
 {
  "title": "Institut Consell de Cent",
  "group": "ESO 2n A",
  "term": "Trimestre 3",
  "subjects": [
   "FÍSICA I QUÍMICA",
   "MATEMÀTIQUES",
   "TECNOLOGIA I DIGITALITZACIÓ",
   "TREBALL GLOBALITZAT",
   "EDUCACIÓ FÍSICA",
   "MÚSICA",
   "OPTATIVA VIP",
   "Aula d'Acollida",
   "LLENG ANGLESA",
   "LLENG CASTELLANA",
   "LLENG CATALANA",
   "LLENG FRANCESA",
   "OPT 3",
   "CIÈNCIES SOCIALS",
   "OPTATIVA TEATRE",
   "OPT 1",
   "OPT 2"
  ],
  "students": [
   {
    "id": 201,
    "grades": {
     "FÍSICA I QUÍMICA": "AS",
     "MATEMÀTIQUES": "NA",
     "TECNOLOGIA I DIGITALITZACIÓ": "NA",
     "TREBALL GLOBALITZAT": null,
     "EDUCACIÓ FÍSICA": "AS",
     "MÚSICA": "NA",
     "OPTATIVA VIP": "AS",
     "Aula d'Acollida": "NA",
     "LLENG ANGLESA": "AS",
     "LLENG CASTELLANA": null,
     "LLENG CATALANA": "NA",
     "LLENG FRANCESA": null,
     "OPT 3": null,
     "CIÈNCIES SOCIALS": "AS",
     "OPTATIVA TEATRE": null,
     "OPT 1": null,
     "OPT 2": null
    },
    "avg": 3.75,
    "fails": 5
   },
   {
    "id": 202,
    "grades": {
     "FÍSICA I QUÍMICA": "AN",
     "MATEMÀTIQUES": "AS",
     "TECNOLOGIA I DIGITALITZACIÓ": "AN",
     "TREBALL GLOBALITZAT": "AS",
     "EDUCACIÓ FÍSICA": "AN",
     "MÚSICA": "AS",
     "OPTATIVA VIP": null,
     "Aula d'Acollida": null,
     "LLENG ANGLESA": "AS",
     "LLENG CASTELLANA": "NA",
     "LLENG CATALANA": "AS",
     "LLENG FRANCESA": "AS",
     "OPT 3": "AS",
     "CIÈNCIES SOCIALS": "AN",
     "OPTATIVA TEATRE": null,
     "OPT 1": null,
     "OPT 2": null
    },
    "avg": 5.79,
    "fails": 1
   },
   {
    "id": 203,
    "grades": {
     "FÍSICA I QUÍMICA": "AS",
     "MATEMÀTIQUES": "NA",
     "TECNOLOGIA I DIGITALITZACIÓ": "NA",
     "TREBALL GLOBALITZAT": "AN",
     "EDUCACIÓ FÍSICA": "AE",
     "MÚSICA": "AE",
     "OPTATIVA VIP": null,
     "Aula d'Acollida": null,
     "LLENG ANGLESA": "AE",
     "LLENG CASTELLANA": "AN",
     "LLENG CATALANA": "AS",
     "LLENG FRANCESA": "AN",
     "OPT 3": "AS",
     "CIÈNCIES SOCIALS": "AN",
     "OPTATIVA TEATRE": null,
     "OPT 1": null,
     "OPT 2": null
    },
    "avg": 6.71,
    "fails": 2
   },
   {
    "id": 204,
    "grades": {
     "FÍSICA I QUÍMICA": "AS",
     "MATEMÀTIQUES": "AS",
     "TECNOLOGIA I DIGITALITZACIÓ": "AS",
     "TREBALL GLOBALITZAT": "AS",
     "EDUCACIÓ FÍSICA": "AS",
     "MÚSICA": "AS",
     "OPTATIVA VIP": null,
     "Aula d'Acollida": null,
     "LLENG ANGLESA": "NA",
     "LLENG CASTELLANA": "NA",
     "LLENG CATALANA": "NA",
     "LLENG FRANCESA": null,
     "OPT 3": "NA",
     "CIÈNCIES SOCIALS": "AS",
     "OPTATIVA TEATRE": "AS",
     "OPT 1": null,
     "OPT 2": null
    },
    "avg": 4.17,
    "fails": 4
   },
   {
    "id": 205,
    "grades": {
     "FÍSICA I QUÍMICA": "AN",
     "MATEMÀTIQUES": "AN",
     "TECNOLOGIA I DIGITALITZACIÓ": "AE",
     "TREBALL GLOBALITZAT": "AN",
     "EDUCACIÓ FÍSICA": "AN",
     "MÚSICA": "AS",
     "OPTATIVA VIP": "AN",
     "Aula d'Acollida": null,
     "LLENG ANGLESA": "AE",
     "LLENG CASTELLANA": "AE",
     "LLENG CATALANA": "AN",
     "LLENG FRANCESA": null,
     "OPT 3": "AN",
     "CIÈNCIES SOCIALS": "AE",
     "OPTATIVA TEATRE": null,
     "OPT 1": null,
     "OPT 2": null
    },
    "avg": 8.25,
    "fails": 0
   },
   {
    "id": 206,
    "grades": {
     "FÍSICA I QUÍMICA": "AS",
     "MATEMÀTIQUES": "AN",
     "TECNOLOGIA I DIGITALITZACIÓ": "AN",
     "TREBALL GLOBALITZAT": "AN",
     "EDUCACIÓ FÍSICA": "AN",
     "MÚSICA": "AN",
     "OPTATIVA VIP": null,
     "Aula d'Acollida": null,
     "LLENG ANGLESA": "AS",
     "LLENG CASTELLANA": "AS",
     "LLENG CATALANA": "AS",
     "LLENG FRANCESA": null,
     "OPT 3": "AS",
     "CIÈNCIES SOCIALS": "AS",
     "OPTATIVA TEATRE": "AN",
     "OPT 1": null,
     "OPT 2": null
    },
    "avg": 6.5,
    "fails": 0
   },
   {
    "id": 207,
    "grades": {
     "FÍSICA I QUÍMICA": "AE",
     "MATEMÀTIQUES": "AN",
     "TECNOLOGIA I DIGITALITZACIÓ": "AE",
     "TREBALL GLOBALITZAT": "AN",
     "EDUCACIÓ FÍSICA": "AN",
     "MÚSICA": "AN",
     "OPTATIVA VIP": null,
     "Aula d'Acollida": null,
     "LLENG ANGLESA": "AS",
     "LLENG CASTELLANA": "AS",
     "LLENG CATALANA": "AS",
     "LLENG FRANCESA": "AS",
     "OPT 3": "AS",
     "CIÈNCIES SOCIALS": "AN",
     "OPTATIVA TEATRE": null,
     "OPT 1": null,
     "OPT 2": null
    },
    "avg": 7.0,
    "fails": 0
   },
   {
    "id": 208,
    "grades": {
     "FÍSICA I QUÍMICA": "AS",
     "MATEMÀTIQUES": "AS",
     "TECNOLOGIA I DIGITALITZACIÓ": "AS",
     "TREBALL GLOBALITZAT": "AS",
     "EDUCACIÓ FÍSICA": "AN",
     "MÚSICA": "AN",
     "OPTATIVA VIP": null,
     "Aula d'Acollida": null,
     "LLENG ANGLESA": "AS",
     "LLENG CASTELLANA": "NA",
     "LLENG CATALANA": "AS",
     "LLENG FRANCESA": null,
     "OPT 3": "NA",
     "CIÈNCIES SOCIALS": "AS",
     "OPTATIVA TEATRE": "AN",
     "OPT 1": null,
     "OPT 2": null
    },
    "avg": 5.33,
    "fails": 2
   },
   {
    "id": 209,
    "grades": {
     "FÍSICA I QUÍMICA": "AS",
     "MATEMÀTIQUES": "AN",
     "TECNOLOGIA I DIGITALITZACIÓ": "AN",
     "TREBALL GLOBALITZAT": "AE",
     "EDUCACIÓ FÍSICA": "AN",
     "MÚSICA": "AS",
     "OPTATIVA VIP": null,
     "Aula d'Acollida": null,
     "LLENG ANGLESA": "AS",
     "LLENG CASTELLANA": "AN",
     "LLENG CATALANA": "AS",
     "LLENG FRANCESA": null,
     "OPT 3": "AN",
     "CIÈNCIES SOCIALS": "AN",
     "OPTATIVA TEATRE": "AN",
     "OPT 1": null,
     "OPT 2": null
    },
    "avg": 7.13,
    "fails": 0
   },
   {
    "id": 210,
    "grades": {
     "FÍSICA I QUÍMICA": "AE",
     "MATEMÀTIQUES": "AE",
     "TECNOLOGIA I DIGITALITZACIÓ": "AE",
     "TREBALL GLOBALITZAT": "AE",
     "EDUCACIÓ FÍSICA": "AE",
     "MÚSICA": "AE",
     "OPTATIVA VIP": null,
     "Aula d'Acollida": null,
     "LLENG ANGLESA": "AN",
     "LLENG CASTELLANA": "AN",
     "LLENG CATALANA": "AN",
     "LLENG FRANCESA": "AN",
     "OPT 3": "AN",
     "CIÈNCIES SOCIALS": "AN",
     "OPTATIVA TEATRE": null,
     "OPT 1": null,
     "OPT 2": null
    },
    "avg": 8.75,
    "fails": 0
   },
   {
    "id": 211,
    "grades": {
     "FÍSICA I QUÍMICA": "AS",
     "MATEMÀTIQUES": "AS",
     "TECNOLOGIA I DIGITALITZACIÓ": "NA",
     "TREBALL GLOBALITZAT": "AN",
     "EDUCACIÓ FÍSICA": "AE",
     "MÚSICA": "AE",
     "OPTATIVA VIP": "AE",
     "Aula d'Acollida": null,
     "LLENG ANGLESA": "AN",
     "LLENG CASTELLANA": "AS",
     "LLENG CATALANA": "AS",
     "LLENG FRANCESA": null,
     "OPT 3": "AS",
     "CIÈNCIES SOCIALS": "AE",
     "OPTATIVA TEATRE": null,
     "OPT 1": null,
     "OPT 2": null
    },
    "avg": 6.79,
    "fails": 1
   },
   {
    "id": 212,
    "grades": {
     "FÍSICA I QUÍMICA": "AE",
     "MATEMÀTIQUES": "AN",
     "TECNOLOGIA I DIGITALITZACIÓ": "AN",
     "TREBALL GLOBALITZAT": "AE",
     "EDUCACIÓ FÍSICA": "AE",
     "MÚSICA": "AE",
     "OPTATIVA VIP": null,
     "Aula d'Acollida": null,
     "LLENG ANGLESA": "AE",
     "LLENG CASTELLANA": "AN",
     "LLENG CATALANA": "AN",
     "LLENG FRANCESA": null,
     "OPT 3": "AE",
     "CIÈNCIES SOCIALS": "AE",
     "OPTATIVA TEATRE": "AE",
     "OPT 1": null,
     "OPT 2": null
    },
    "avg": 9.0,
    "fails": 0
   },
   {
    "id": 213,
    "grades": {
     "FÍSICA I QUÍMICA": "NA",
     "MATEMÀTIQUES": null,
     "TECNOLOGIA I DIGITALITZACIÓ": "NA",
     "TREBALL GLOBALITZAT": null,
     "EDUCACIÓ FÍSICA": null,
     "MÚSICA": null,
     "OPTATIVA VIP": null,
     "Aula d'Acollida": null,
     "LLENG ANGLESA": null,
     "LLENG CASTELLANA": null,
     "LLENG CATALANA": null,
     "LLENG FRANCESA": "NA",
     "OPT 3": "NA",
     "CIÈNCIES SOCIALS": "NA",
     "OPTATIVA TEATRE": null,
     "OPT 1": null,
     "OPT 2": null
    },
    "avg": 2.5,
    "fails": 5
   },
   {
    "id": 214,
    "grades": {
     "FÍSICA I QUÍMICA": "AS",
     "MATEMÀTIQUES": "AN",
     "TECNOLOGIA I DIGITALITZACIÓ": "AS",
     "TREBALL GLOBALITZAT": null,
     "EDUCACIÓ FÍSICA": "AN",
     "MÚSICA": "AS",
     "OPTATIVA VIP": "AS",
     "Aula d'Acollida": "AN",
     "LLENG ANGLESA": "AN",
     "LLENG CASTELLANA": "AS",
     "LLENG CATALANA": "AE",
     "LLENG FRANCESA": null,
     "OPT 3": null,
     "CIÈNCIES SOCIALS": "AN",
     "OPTATIVA TEATRE": null,
     "OPT 1": null,
     "OPT 2": null
    },
    "avg": 6.77,
    "fails": 0
   },
   {
    "id": 215,
    "grades": {
     "FÍSICA I QUÍMICA": "AN",
     "MATEMÀTIQUES": "AS",
     "TECNOLOGIA I DIGITALITZACIÓ": "AS",
     "TREBALL GLOBALITZAT": "AS",
     "EDUCACIÓ FÍSICA": "AN",
     "MÚSICA": "AS",
     "OPTATIVA VIP": null,
     "Aula d'Acollida": null,
     "LLENG ANGLESA": "AS",
     "LLENG CASTELLANA": "AS",
     "LLENG CATALANA": "AS",
     "LLENG FRANCESA": null,
     "OPT 3": "AS",
     "CIÈNCIES SOCIALS": "AN",
     "OPTATIVA TEATRE": "AS",
     "OPT 1": null,
     "OPT 2": null
    },
    "avg": 5.75,
    "fails": 0
   },
   {
    "id": 216,
    "grades": {
     "FÍSICA I QUÍMICA": "AN",
     "MATEMÀTIQUES": "AN",
     "TECNOLOGIA I DIGITALITZACIÓ": "AS",
     "TREBALL GLOBALITZAT": "AN",
     "EDUCACIÓ FÍSICA": "AN",
     "MÚSICA": "AE",
     "OPTATIVA VIP": null,
     "Aula d'Acollida": null,
     "LLENG ANGLESA": "AN",
     "LLENG CASTELLANA": "AE",
     "LLENG CATALANA": "AN",
     "LLENG FRANCESA": null,
     "OPT 3": "AN",
     "CIÈNCIES SOCIALS": "AN",
     "OPTATIVA TEATRE": "AE",
     "OPT 1": null,
     "OPT 2": null
    },
    "avg": 8.13,
    "fails": 0
   },
   {
    "id": 217,
    "grades": {
     "FÍSICA I QUÍMICA": "AS",
     "MATEMÀTIQUES": "AS",
     "TECNOLOGIA I DIGITALITZACIÓ": "AS",
     "TREBALL GLOBALITZAT": "AS",
     "EDUCACIÓ FÍSICA": "AN",
     "MÚSICA": "AS",
     "OPTATIVA VIP": "AS",
     "Aula d'Acollida": null,
     "LLENG ANGLESA": "AN",
     "LLENG CASTELLANA": "AS",
     "LLENG CATALANA": "AS",
     "LLENG FRANCESA": null,
     "OPT 3": "AS",
     "CIÈNCIES SOCIALS": "AS",
     "OPTATIVA TEATRE": null,
     "OPT 1": null,
     "OPT 2": null
    },
    "avg": 5.5,
    "fails": 0
   },
   {
    "id": 218,
    "grades": {
     "FÍSICA I QUÍMICA": "AS",
     "MATEMÀTIQUES": "AS",
     "TECNOLOGIA I DIGITALITZACIÓ": "AS",
     "TREBALL GLOBALITZAT": "AS",
     "EDUCACIÓ FÍSICA": "AS",
     "MÚSICA": "AN",
     "OPTATIVA VIP": "AS",
     "Aula d'Acollida": null,
     "LLENG ANGLESA": "AN",
     "LLENG CASTELLANA": "NA",
     "LLENG CATALANA": "AS",
     "LLENG FRANCESA": null,
     "OPT 3": "AS",
     "CIÈNCIES SOCIALS": "AS",
     "OPTATIVA TEATRE": null,
     "OPT 1": null,
     "OPT 2": null
    },
    "avg": 5.29,
    "fails": 1
   }
  ]
 }
];